### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by GargAnshu9468** [ParthJadhav/Tkinter-Designer#43] opened 2021-06-19 12:54 UTC
How to Fix ?
A key error occurs when the elements are named or grouped incorrectly. Before creating an issue, make sure that you have followed the [instructions](https://github.com/ParthJadhav/Tkinter-Designer/blob/master/docs/instructions.md) guide correctly.  

If the issue still persists, create an issue with the following details included.

1. Error Message
2. Link to the Figma File

**Comment by ParthJadhav** [comment] 2021-06-19 12:54
Thanks for creating an issue, we are eager to solve it.

**Comment by GargAnshu9468** [comment] 2021-06-19 12:58
1. Error Message -

list index out of range
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\akgar\AppData\Local\Programs\Python\Python38\lib\tkinter\__init__.py", line 1883, in __call__
    return self.func(*args)
  File "tkinter_designer.py", line 26, in btn_clicked
    backend.generate_code(token, URL, output_path)
  File "E:\Tkinter Designer\backend.py", line 113, in generate_code
    window_elements = fig_window["children"]
KeyError: 'children'

2. Figma File Link

https://www.figma.com/file/4FZIcoZMFI1DbaZS2toJNg/Untitled?node-id=0%3A1

**Comment by ParthJadhav** [comment] 2021-06-19 13:10
Thanks for the information. Let me check.

**Comment by ParthJadhav** [comment] 2021-06-19 13:21
Hey @GargAnshu9468, I don't have access to my pc right now. But Can you try delete the element I've marked.

![image](https://user-images.githubusercontent.com/42001064/122643764-4965ab80-d12f-11eb-9abf-223cf9338033.jpeg)

**Comment by ParthJadhav** [comment] 2021-06-19 13:26
If it doesn't work, give me some time until I get back my pc.

Until then try some of the templates, I created.

https://www.figma.com/@parthjadhav
Select the design and click duplicate.

**Comment by ParthJadhav** [comment] 2021-06-19 17:13
Did it work @GargAnshu9468 ?

**Comment by GargAnshu9468** [comment] 2021-06-20 10:26
I have removed that element named "Vector" as you told me but now the new error arises as shown below and also I have tried all your designs by duplicating them but when I was trying to get the tkinter code of them using tkinter designer then I have got the same error. 

Error Message -

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\akgar\AppData\Local\Programs\Python\Python38\lib\tkinter\__init__.py", line 1883, in __call__
    return self.func(*args)
  File "tkinter_designer.py", line 29, in btn_clicked
    backend.generate_code(token,URL, output_path)
  File "C:\Users\akgar\Downloads\Tkinter-Designer-master\Tkinter-Designer-master\backend.py", line 168, in generate_code
    image_link = requests.get(response.json()["images"][item_id])
  File "C:\Users\akgar\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\akgar\AppData\Local\Programs\Python\Python38\lib\site-packages\simplejson\__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "C:\Users\akgar\AppData\Local\Programs\Python\Python38\lib\site-packages\simplejson\decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "C:\Users\akgar\AppData\Local\Programs\Python\Python38\lib\site-packages\simplejson\decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
  File "C:\Users\akgar\AppData\Local\Programs\Python\Python38\lib\site-packages\simplejson\scanner.py", line 79, in scan_once
    return _scan_once(string, idx)
  File "C:\Users\akgar\AppData\Local\Programs\Python\Python38\lib\site-packages\simplejson\scanner.py", line 70, in _scan_once
    raise JSONDecodeError(errmsg, string, idx)
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by ParthJadhav** [comment] 2021-06-20 10:29
Yes @GargAnshu9468 , I have encountered that error too. It's happening since morning. It's a server side problem from Figma.

We can't do anything about it. I get  it work by retrying. There's nothing else we can do...

**Comment by GargAnshu9468** [comment] 2021-06-20 10:30
Oh Is It? Okay Then. Thank You !!

**Comment by ParthJadhav** [comment] 2021-06-20 10:31
I guess they should fix it soon. 
Sorry for the inconvenience.

**Comment by GargAnshu9468** [comment] 2021-06-20 10:34
It's Okay. Can you help me one more time? Actually as you can see that I have made all elements as components so that's okay or not okay? And if it is not okay then how can I revert component back to normal element?

**Comment by ParthJadhav** [comment] 2021-06-20 10:36
I haven't tried components with Tkinter Designer. Let me try and then I'll tell you. Give me a minute.

**Comment by GargAnshu9468** [comment] 2021-06-20 10:37
Okay.

**Comment by ParthJadhav** [comment] 2021-06-20 10:57
Hey @GargAnshu9468, Components work but they don't get the correct colours. So using components is not recommended. Also it took me around 6 tries to get it working due to JSON decode errors.

To remove the component you need to duplicate the current component and then click the three dots on the right side below the coordinates and click detach. But this will keep the component in a group which again will cause errors.

Rather try recreating the design. It would take less time.

**Comment by GargAnshu9468** [comment] 2021-06-20 11:03
Okay! Thanks.

**Comment by ParthJadhav** [comment] 2021-06-21 03:59
Hey @GargAnshu9468 , Is the JSON Decoder error gone ?

**Comment by ParthJadhav** [comment] 2021-06-21 04:00
Hey @GargAnshu9468 , Is the JSON Decoder error gone ?

**Comment by GargAnshu9468** [comment] 2021-06-21 08:12
Yeah! But the new error arises as mention below -

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\akgar\AppData\Local\Programs\Python\Python38\lib\tkinter\__init__.py", line 1883, in __call__
    return self.func(*args)
  File "e:\Tkinter Designer\tkinter_designer.py", line 26, in btn_clicked
    backend.generate_code(token, URL, output_path)
  File "e:\Tkinter Designer\backend.py", line 160, in generate_code
    bg = get_color(element)
  File "e:\Tkinter Designer\backend.py", line 10, in get_color
    el_r = element["fills"][0]["color"]['r'] * 255
IndexError: list index out of range

**Comment by ParthJadhav** [comment] 2021-06-21 08:13
Sure, that error is easy to solve. Can you share me link to your Figma file?

**Comment by GargAnshu9468** [comment] 2021-06-21 08:13
Figma File Link -

https://www.figma.com/file/4FZIcoZMFI1DbaZS2toJNg/Tkinter-Designer-UI?node-id=0%3A1

**Comment by ParthJadhav** [comment] 2021-06-21 08:14
Let me take a look

**Comment by GargAnshu9468** [comment] 2021-06-21 08:15
Okay. Thanks.

**Comment by ParthJadhav** [comment] 2021-06-21 08:17
Can you try now ? @GargAnshu9468

**Comment by GargAnshu9468** [comment] 2021-06-21 08:18
Okay. Wait a minute please!

**Comment by GargAnshu9468** [comment] 2021-06-21 08:23
Code has generated but an issue occurs. See 

File ".\window.py", line 36
SyntaxError: Non-UTF-8 code starting with '\x92' in file .\window.py on line 36, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

**Comment by ParthJadhav** [comment] 2021-06-21 08:24
@GargAnshu9468 Let me see

**Comment by GargAnshu9468** [comment] 2021-06-21 08:25
Okay.

**Comment by GargAnshu9468** [comment] 2021-06-21 08:29
Done. It's working now.

**Comment by ParthJadhav** [comment] 2021-06-21 08:30
Hey @GargAnshu9468 I am not able to reproduce that issue. The file is created and running just has some alignment issues but that's not a problem.

**Comment by ParthJadhav** [comment] 2021-06-21 08:30
Oh Okay !

**Comment by GargAnshu9468** [comment] 2021-06-21 08:30
Thank You So Much.

**Comment by ParthJadhav** [comment] 2021-06-21 08:31
Also keep in mind if you want text on next line then press enter or else it will consider it as single line even if it looks like diffrent lines

**Comment by GargAnshu9468** [comment] 2021-06-21 08:31
Okay. Noted.

**Comment by ParthJadhav** [comment] 2021-06-21 08:33
You can try some templates -
https://www.figma.com/@parthjadhav

But they only work with experimental branch. I would be merging that branch with master in few days. But it has some new features. You can try it out. 

But if you use it, use it only with templates.

**Comment by ParthJadhav** [comment] 2021-06-21 08:34
Anyways, If your problem is solved, Can I close this issue ?

**Comment by ParthJadhav** [comment] 2021-06-21 08:34
Anyways, If your problem is solved, Can I close this issue ?

**Comment by GargAnshu9468** [comment] 2021-06-21 08:46
One last thing I want to know that their are many major differences between the design and the actual output. So can you tell me why?

**Comment by ParthJadhav** [comment] 2021-06-21 12:52
Like ?

**Closed** 2021-06-27 06:27 UTC
