### ISSUE TITLE
Grey Frames generate on each elements

### ISSUE THREAD

**Issue by Xam-Mlr** [ParthJadhav/Tkinter-Designer#123] opened 2021-08-17 16:54 UTC
Hello, I have just test your project which works very well except of grey frames (input) which are generate on each element and therefore we can't see the elements.
Do you know how to solve the problem ?
Thanks

**Comment by neilbaldwin** [comment] 2021-08-19 09:57
Could you upload a screengrab here so we can see more clearly what the problem is? Also could you copy and paste the text output from the tool in case there are any errors?

**Comment by jvendegna** [comment] 2021-09-04 15:35
@Xam-Mlr are you still in need of assistance?

**Comment by Xam-Mlr** [comment] 2021-09-04 20:38
Yes

**Comment by jvendegna** [comment] 2021-09-04 21:10
Sure, can you provide the screenshot and command output as requested please.

**Comment by Xam-Mlr** [comment] 2021-09-05 06:36
> Sure, can you provide the screenshot and command output as requested please.

![image](https://user-images.githubusercontent.com/71919327/132117906-0c3b774d-3094-440b-a353-f759ddfe46fd.jpeg)
![image](https://user-images.githubusercontent.com/71919327/132117909-299e7ee7-79ef-400a-b123-adac4166dfcb.jpeg)

**Comment by jvendegna** [comment] 2021-09-06 05:10
Please read the [instructions](https://github.com/ParthJadhav/Tkinter-Designer/blob/master/docs/instructions.md#2-element-guide) and ensure you're using the latest version. From what I can see, all the properly named and formatted items are showing up correctly. We have no element called TextBox, for example.

**Comment by jvendegna** [comment] 2021-09-06 05:47
Closing. You're not participating as requested. Your interactions are minimal, and off-putting at best. I do this in my free time, and I have no patience for those who won't help me help them. Goodbye.

**Comment by jvendegna** [comment] 2021-09-06 07:39
Okay, can you provide the command output as well, and a screenshot with each element in figma selected may help as well. I apologize for closing this earlier and marking it invalid. I'll try to be as helpful as I can with the information you provide.

**Comment by jvendegna** [comment] 2021-09-10 07:32
Closing for inactivity.

**Closed by jvendegna** 2021-09-10 07:32 UTC
Labels: question
