### ISSUE TITLE
Text isnt scaling properly?

### ISSUE THREAD

**Issue by jcjakec** [ParthJadhav/Tkinter-Designer#78] opened 2021-07-16 21:38 UTC
https://imgur.com/hsLfcXp
This shows the figma work
https://imgur.com/SmbJDxG 
This shows what happens when I run window.py

And when I lower the text size, this happens:
https://imgur.com/5HkynwT

Help appreciated! Love the work though, this is making GUI's 10x nicer and easier.

**Comment by ParthJadhav** [comment] 2021-07-17 01:46
https://github.com/ParthJadhav/Tkinter-Designer/issues/68 

Here's the issue in which the text positioning is solved. And the text sizing issue is not due to the tool it's because the difference between the OS and how it renders the text.

https://stackoverflow.com/questions/62263114/tkinter-python-3-scaling-issue-on-macos

You need to manually reduce the size of the text on figma then read the solutions on the issue mentioned above. The code solution is not implemented yet buy there are some easy ways to solve mentioned in that issue.

**Comment by saur0x** [comment] 2021-07-21 17:19
@jcjakec Can you test out the new changes in #87 and verify if it fixes your problem?

**Comment by ParthJadhav** [comment] 2021-07-23 05:15
Hey @jcjakec you can close the issue if the problem is solved.

**Closed** 2021-07-24 14:57 UTC
