### ISSUE TITLE
The code created by Tkinter-Designer does not show the Design file I created in Figma

### ISSUE THREAD

**Issue by AlkisPis** [ParthJadhav/Tkinter-Designer#42] opened 2021-06-19 11:30 UTC
I have created a Design file in Figma, following the steps of the Element Guide as described in _https://github.com/ParthJadhav/Tkinter-Designer/blob/master/docs/instructions.md_
The created page (File URL) is **https://www.figma.com/file/UEuqWZxlkkHvXGP5VC19Rl/File_01?node-id=0%3A1**
I give this and my Token ID in 'tkinter_designer.py' and a 'window.py' file is created, as expected.  When I run it, I see just an empty Tkinter window. I checked the file and it doesn't even contain the name "Alkis Piskas" which is stored as text in the Design file and which can be seen in the above mentioned File URL. Shouldn't the code be able to reproduce the content of  the Design File?

**Comment by ParthJadhav** [comment] 2021-06-19 11:34
Hey @AlkisPis, There were some problems in the design - 

1. The X and Y coordinates of the frame were not 0.
2. All the elements were grouped into a single element.

I have fixed those problems Check this link-
https://www.figma.com/file/vxJe6y25HfOZXdQFUBpeF6/Fixed?node-id=0%3A1


<img width="281" alt="Screenshot 2021-06-19 at 5 03 14 PM" src="https://user-images.githubusercontent.com/42001064/122641020-3e574f00-d120-11eb-92e4-b9ad6fbdcf9d.png">

**Comment by ParthJadhav** [comment] 2021-06-19 11:42
Here's the result !

<img width="1013" alt="Screenshot 2021-06-19 at 5 12 07 PM" src="https://user-images.githubusercontent.com/42001064/122641217-7ca13e00-d121-11eb-8bf2-47e0cfb482fc.png">

**Comment by ParthJadhav** [comment] 2021-06-19 11:53
I am create a workaround that Frame coordinates problem.

**Comment by ParthJadhav** [comment] 2021-06-19 12:08
Hey @AlkisPis,

Now you don't need to care about the frame's coordinate being 0. I have added the fix in the latest commit, so you'll need to fetch the changes.

**Comment by AlkisPis** [comment] 2021-06-19 14:34
Hi!

Thanks. Is this a screenshot of the webpage ot the created PY code? 
Because, actually the corners of the rectangle are rounded. This is (part of) what the webpage at https://www.figma.com/file/UEuqWZxlkkHvXGP5VC19Rl/File_01?node-id=0%3A1 shows: 
BTW (referring to two later emails of yours), what do the coordinates have to do with the problem I posted?  

Alkis

Sent from Mail for Windows 10

**Comment by ParthJadhav** [comment] 2021-06-19 14:49
Currently rounded rectangles are not supported. 

The X and Y position of the frame used to matter because the Figma API returns the position of the elements relative to the outer canvas. But we want the position relative to the frame. So when we created the code, the elements had their coordinates relative to the canvas. Which caused the elements to disappear out of the tkinter window. 

So we used to set the position position of the Frame to 0 so the values would be correct.

But I have fixed that now. By subtracting the coordinates of the frame from the coordinates of the elements.

**Comment by AlkisPis** [comment] 2021-06-19 15:00
OK. But I have no problem with Figma and the design iitself. I have already told that in the webpage everything is OK. I talked about the generated code.

Please see tha attached PY file created by Tkinter-Designer. (I had to rename it to .txt because my stupid emailer doesn’t accept this file extention!) 
Not even the text “Alkis Piskas” is in there …

Alkis

Sent from Mail for Windows 10

**Comment by ParthJadhav** [comment] 2021-06-19 15:27
That's what I am telling 😅 I have fixed those issues in the link that I sent. And the screenshot I sent was of the generated file. 

Also the issue of the frame coordinates has fixed in the latest commit. Make sure that you are using that.

**Comment by ParthJadhav** [comment] 2021-06-19 15:28
Also you can use GitHub to upload files. It supports everything 😄

**Comment by AlkisPis** [comment] 2021-06-19 15:38
Right! 😀

Sent from Mail for Windows 10

**Comment by AlkisPis** [comment] 2021-06-19 15:46
I checked Github again in case you have uploaded a new version  of 'tkinter_designer.py', I downloaded it and tried. Didn’t get a different result … Is it me?

Here are my data:
Token ID: 197248-cc73063d-84b8-40ac-a271-8a01821f3a70
File URL: https://www.figma.com/file/UEuqWZxlkkHvXGP5VC19Rl/File_01?node-id=1%3A1 (or … A2)

Did you do the same thing (with a different token)?
If you use exactly the data I laid out above, then … It’s just me! 😀

Alkis

Sent from Mail for Windows 10

**Comment by AlkisPis** [comment] 2021-06-19 15:57
I used the new File URL you gave me, and what do you know? It works!
You made it! 👍

Thanks

Cheers
Alkis 

Sent from Mail for Windows 10

**Comment by ParthJadhav** [comment] 2021-06-19 15:58
Hey,
@AlkisPis the problem is about grouping. I again checked the link that you sent and the contents are not updated according to the link I sent. 

Can you give me the editing permissions to the file so I can change the properties directly ?

### Your File.
<img width="282" alt="Screenshot 2021-06-19 at 9 26 09 PM" src="https://user-images.githubusercontent.com/42001064/122648077-fe569300-d144-11eb-8da7-72bb17ac4eef.png">

### Your File which I fixed.
<img width="281" alt="Screenshot 2021-06-19 at 9 26 54 PM" src="https://user-images.githubusercontent.com/42001064/122648093-14645380-d145-11eb-860f-94df4e59c679.png">

**Comment by ParthJadhav** [comment] 2021-06-19 15:59
> I used the new File URL you gave me, and what do you know? It works! You made it! 👍 

Oh, Great ! 
It's just a game of Naming which usually get's wrong, That's why I am working on removing that game altogether 😄

**Comment by ParthJadhav** [comment] 2021-06-19 16:07
Also one more thing @AlkisPis, 

The sizing of the window also important. While creating designs on an Infinite canvas we don't usually get how big we are creating the frame and it usually becomes bigger than the actual screen size of our devices. which also causes invisible elements.

**Comment by ParthJadhav** [comment] 2021-06-19 16:19
Now in the latest commit Tkinter Designer informs you about invalid elements.

<img width="703" alt="Screenshot 2021-06-19 at 9 48 07 PM" src="https://user-images.githubusercontent.com/42001064/122648730-1bd92c00-d148-11eb-9e9b-fd355768fecf.png">

**Comment by AlkisPis** [comment] 2021-06-20 11:22
Hi

Re: “Can you give me the editing permissions to the file so I can change the properties directly”: Of course (I have already moved the file in a team (“My Team”). I don’t know though how this works and if I have done it correctly … I also received the link you send me your “fixed” version, which I tested and it worked fine.

Alkis

**Comment by ParthJadhav** [comment] 2021-06-20 11:25
Yes, But the Figma API is not working correctly today. Many people are getting JSON Decoder Error which is caused by incorrect JSON file and also Status code 504.

**Closed** 2021-06-22 04:06 UTC
