### ISSUE TITLE
Inconvenient instructions

### ISSUE THREAD

**Issue by KrazyKirby99999** [ParthJadhav/Tkinter-Designer#5] opened 2021-05-27 19:20 UTC
Those interested in using Tkinter-Designer are currently required to download a pdf file from google drive, rather than simply reading from github. The instructions for installing are near the bottom of the pdf, which makes it even more inconvenient. I suggest converting each slide to an image, and creating at markdown file that is included within this repository.

**Comment by ParthJadhav** [comment] 2021-05-28 01:16
I understand for the inconvenience caused by the instruction, I’ll be adding the installation instructions in the readme and be uploading a tutorial video too.

and I’ll be creating different readme with Figma instructions in it.

**Comment by piccoloser** [comment] 2021-05-28 04:24
If you need an editor to review and/or revise the PDF once it's done, I'd be glad to help out!

**Comment by ParthJadhav** [comment] 2021-05-28 04:30
Thanks, btw would you be able to create a tutorial video ?

**Comment by ParthJadhav** [comment] 2021-05-28 04:34
> If you need an editor to review and/or revise the PDF/README once it's done, I'd be glad to help out!

Also do you use Apple Keynote ? It would enable you to collaborate on the PDF.

**Comment by piccoloser** [comment] 2021-05-28 05:21
I don't use Keynote, but I have Adobe Acrobat. If collaboration doesn't work out I can still review/edit the draft, whatever works best.

**Comment by ParthJadhav** [comment] 2021-05-28 05:25
I think it would be better if I create a video directly. It would be more easy for the users.

**Comment by ParthJadhav** [comment] 2021-05-28 14:17
@piccoloser Would you Make the md ?

**Comment by piccoloser** [comment] 2021-05-28 14:54
Yeah, I can certainly do that!

**Comment by ParthJadhav** [comment] 2021-05-28 15:42
Thanks, create a pull request when done ✅

**Comment by piccoloser** [comment] 2021-05-28 17:42
[instructions.md](https://github.com/ParthJadhav/Tkinter-Designer/files/6562495/instructions.md)

I think this is probably the best instructions file I've ever written lol. There aren't any images, but I think it's alright as-is. Feel free to add or change it as you see fit!

**Comment by piccoloser** [comment] 2021-05-28 17:46
Also, while I was writing this, I made a dummy file to test the process out, and I didn't include a Frame in the Design file, which caused the program to fail without notifying me through the UI. I'll create an issue for this.

**Comment by ParthJadhav** [comment] 2021-05-29 04:12
I think with this Pull Request the instructions have become clear and understandable. 
Closing this issue, Reopen if you want @KrazyKirby99999

**Closed by ParthJadhav** 2021-05-29 04:12 UTC
