### ISSUE TITLE
Fonts not showing right.

### ISSUE THREAD

**Issue by Vinyzu** [ParthJadhav/Tkinter-Designer#106] opened 2021-07-30 08:13 UTC
Yo, i was trying to use some fonts like "Iceberg", but for mostof them, they dont show up right, most oif them, if not such popular like "Helvetica" or so, the font doesnt work...

**Comment by ParthJadhav** [comment] 2021-07-30 08:20
The font you are using on your design must be installed on your machine...

**Comment by ParthJadhav** [comment] 2021-07-30 08:21
And popular fonts work because they are installed by default on most operating systems.

**Comment by ParthJadhav** [comment] 2021-07-31 12:11
you can close the issue if the problem is solved :)

**Comment by ParthJadhav** [comment] 2021-07-31 12:12
Oops, I Closed it...

**Closed** 2021-08-02 06:06 UTC
