### ISSUE TITLE
Just keeps buffering

### ISSUE THREAD

**Issue by dontbanmeplz** [ParthJadhav/Tkinter-Designer#48] opened 2021-06-21 02:26 UTC
Window goes into "not responding" right after running and never finnishes

**Comment by ParthJadhav** [comment] 2021-06-21 02:27
Thanks for creating an issue, we are eager to solve it.

**Comment by dontbanmeplz** [comment] 2021-06-21 02:27
thank you

**Comment by dontbanmeplz** [comment] 2021-06-21 02:28
thank you for making this, it has spurred me to start an old project because i couldn't make a GUI normally.

**Comment by ParthJadhav** [comment] 2021-06-21 03:07
Yes @dontbanmeplz , It's creating the code while it's in not responding and you should wait. But if you get JSON decode error which most people are experiencing from yesterday is caused by Figma API which makes the process longer and eventually fails. Only way is to retrying. It's a server side error from Figma and It should be fixed.

Sorry for inconvenience.

**Comment by ParthJadhav** [comment] 2021-06-22 10:10
It must have been solved now @dontbanmeplz

**Closed** 2021-06-27 06:27 UTC
